import { Food } from './app/models/food';


export const foods: Food[] =
[
  {
      id: 1,
      name: 'Combo Meal',
      promo: '20% off',
      price: 4.5,
      icon: 'sandwich.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 2,
      name: 'Burgers & Sandiches',
      promo: '',
      price: 5,
      icon: 'birthday-cake.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 3,
      name: 'Happy Meal',
      promo: '',
      price: 4.2,
      icon: 'burger.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 4,
      name: 'Beverages',
      promo: '',
      price: 2,
      icon: 'burger.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 5,
      name: 'Chicken',
      promo: '',
      price: 4,
      icon: 'chicken-leg.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 6,
      name: 'Snack & Sides',
      promo: '',
      price: 4,
      icon: 'chicken-leg.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 7,
      name: 'Big Meal',
      promo: '20% off',
      price: 4.5,
      icon: 'burger.svg',
      cat: 'product',
      menu: [1, 2],
      number: 1,
  },
  {
      id: 8,
      name: 'Quarter Pounder',
      promo: '',
      price: 5,
      icon: 'hot-dog.svg',
      cat: 'product',
      menu: [6],
      number: 1,
  },
  {
      id: 9,
      name: 'Cheeseburger',
      promo: '',
      price: 4.2,
      icon: 'pizza.svg',
      cat: 'product',
      number: 1,
  },
  {
      id: 10,
      name: 'Crispy Chicken',
      promo: '',
      price: 2,
      icon: 'chicken-leg.svg',
      cat: 'menu',
      number: 1,
  },
  {
      id: 11,
      name: 'Sausage sausage',
      promo: '',
      price: 4,
      icon: 'birthday-cake.svg',
      cat: 'product',
      number: 1,
  },
  {
      id: 12,
      name: 'Filet-o-Fish',
      promo: '',
      price: 4,
      icon: 'roast-chicken.svg',
      cat: 'product',
      number: 1,
  }
];
